# Based on https://github.com/morhetz/gruvbox by morhetz <morhetz@gmail.com>
# Adapted to kitty by wdomitrz <witekdomitrz@gmail.com>
# Ported to ilyasyoy colorscheme

cursor                  #bcbcbc
cursor_text_color       background

url_color               #5f87af

visual_bell_color       #87af87
bell_border_color       #87af87

active_border_color     #d787af
inactive_border_color   #444444

foreground              #bcbcbc
background              #000000
selection_foreground    #000000
selection_background    #5f87af

active_tab_foreground   #bcbcbc
active_tab_background   #444444
inactive_tab_foreground #767676
inactive_tab_background #262626

# black  (bg3/bg4)
color0                  #444444
color8                  #585858

# red
color1                  #d75f5f
color9                  #d75f5f

# green
color2                  #87af87
color10                 #87af87

# yellow
color3                  #d7875f
color11                 #d7875f

# blue
color4                  #5f87af
color12                 #5f87af

# purple
color5                  #d787af
color13                 #d787af

# aqua
color6                  #8787af
color14                 #8787af

# white (fg4/fg3)
color7                  #bcbcbc
color15                 #bcbcbc
