[[language]]
name = "python"
language-servers = ["pyright"]

[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]

[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]

[[language]]
name = "html"
language-servers = ["vscode-html-language-server"]

[[language]]
name = "css"
language-servers = ["vscode-css-language-server"]

[[language]]
name = "json"
language-servers = ["vscode-json-language-server"]

[[language]]
name = "bash"
language-servers = ["bash-language-server"]

[[language]]
name = "c"
language-servers = ["clangd"]

[[language]]
name = "cpp"
language-servers = ["clangd"]

[[language]]
name = "go"
language-servers = ["gopls"]

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]

[[language]]
name = "java"
language-servers = ["jdtls"]

[[language]]
name = "lua"
language-servers = ["lua-language-server"]

[[language]]
name = "yaml"
language-servers = ["yaml-language-server"]

[[language]]
name = "toml"
language-servers = ["taplo"]

[[language]]
name = "markdown"
language-servers = ["marksman"]

[[language]]
name = "dockerfile"
language-servers = ["docker-langserver"]
