[colors]
primary.background = "#ffffff"
primary.foreground = "#404040"

[colors.normal]
black   = "#767676"
red     = "#d75f5f"
green   = "#5f9c5f"
yellow  = "#d7875f"
blue    = "#5f87af"
magenta = "#d787af"
cyan    = "#8787af"
white   = "#bcbcbc"

[colors.bright]
black   = "#b0b0b0"
red     = "#d75f5f"
green   = "#87af87"
yellow  = "#d7875f"
blue    = "#5f87af"
magenta = "#d787af"
cyan    = "#8787af"
white   = "#585859"
